spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/underdog_test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      highlight_sql: true
      format_sql: true
      ddl-auto: create
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
        springframework:
          orm:
            jpa: DEBUG
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_PASSWORD}
            scope:
              - email
              - profile
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_PASSWORD}
            scope:
              - email
              - profile
          facebook:
            clientId: ${F_CLIENT_ID}
            clientSecret: ${F_CLIENT_PASSWORD}
            scope:
              - email
              - profile

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: ${MAIL_ADDRESS_ADMIN}