= Underdog-Pre-Project
:sectnums:
:toc: left
:toclevels: 4
:toc-title: Underdog
:source-highlighter: prettify

[[User-API]]
== User API

=== 회원 등록
operation::post-user[snippets='http-request,http-response,response-headers,request-fields']

[[Answer-API]]
== Answer API

=== 답변 등록
operation::post-answer[snippets='http-request,http-response,response-headers,request-fields,path-parameters']
=== 답변 수정
operation::patch-answer[snippets='http-request,http-response,request-fields,path-parameters']
=== 답변 조회
operation::get-answer[snippets='path-parameters,http-response,response-fields']
=== 답변 삭제
operation::delete-answer[snippets='http-request,path-parameters']

[[Answer-Comment-API]]
== Answer Comment API

=== 답변 댓글 등록
operation::post-answer-comment[snippets='http-request,http-response,response-headers,request-fields,path-parameters']
=== 답변 댓글 수정
operation::patch-answer-comment[snippets='http-request,http-response,request-fields,path-parameters']
=== 답변 댓글 조회
operation::get-answer-comment[snippets='path-parameters,http-response,response-fields']
=== 답변 댓글 삭제
operation::delete-answer-comment[snippets='http-request,path-parameters']

[[Answer-Vote-API]]
== Answer Vote API

=== 답변 좋아요 등록
operation::post-answer-vote[snippets='http-request,http-response,path-parameters']
=== 답변 좋아요 삭제
operation::delete-answer-vote[snippets='http-request,path-parameters']

[[Question-API]]
== Question API

=== 질문 등록
operation::post-question[snippets='http-request,http-response,response-headers,request-fields']
=== 질문 수정
operation::patch-question[snippets='http-request,http-response,request-fields,path-parameters']
=== 질문 조회
operation::get-question[snippets='path-parameters,http-response,response-fields']
=== 질문 전체 조회
operation::get-questions[snippets='http-response,response-fields']
=== 질문 삭제
operation::delete-question[snippets='http-request,path-parameters']

[[Question-Comment-API]]
== Question Comment API

=== 질문 댓글 등록
operation::post-question-comment[snippets='http-request,http-response,response-headers,request-fields,path-parameters']
=== 질문 댓글 수정
operation::patch-question-comment[snippets='http-request,http-response,request-fields,path-parameters']
=== 질문 댓글 조회
operation::get-question-comments[snippets='path-parameters,http-response,response-fields']
=== 질문 댓글 삭제
operation::delete-question-comment[snippets='http-request,path-parameters']

[[Question-Vote-API]]
== Question Vote API

=== 질문 좋아요 등록
operation::post-question-vote[snippets='http-request,http-response,path-parameters']
=== 질문 좋아요 삭제
operation::delete-vote[snippets='http-request,path-parameters']

[[Question-Tag-API]]
== Question Tag API

=== 질문 태그 등록
operation::post-tag[snippets='http-request,http-response,path-parameters']
=== 질문 태그 조회
operation::get-questionTag[snippets='path-parameters,http-response,response-fields']

